dartallapy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('dtlauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('dtluser.urls')),
    path('scrapy/', include('dtlscrapy.urls')),
    path('polls/', include('polls.urls')),
    path('customer/', include('dtlcustomer.urls')),
]

dtluser/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
	path('', views.profile , name="profile"),
	path('register/', views.register , name="register"),
	path('edit/', views.edit , name="edit"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from .import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

dtluser/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	picture = models.ImageField(default='default.jpg', upload_to='profile_pics')
	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

dtluser/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(
		required=True,
		widget=forms.TextInput(
			attrs={'class': 'form-control'}
		)
	)
	username = forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control'
		}
	))
	first_name = forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control'
		}
	))
	last_name = forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control'
		}
	))
	password1 = forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control'
		}
	))
	password2 = forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control'
		}
	))

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2',
		)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class ChangeForm(UserChangeForm):
	first_name = forms.CharField()
	first_name.widget.attrs.update({'class': 'form-control'})
	first_name.label = 'Nome'

	last_name = forms.CharField()
	last_name.widget.attrs.update({'class': 'form-control'})
	last_name.label = 'Sobrenome'

	email = forms.EmailField()
	email.widget.attrs.update({'class': 'form-control'})
	email.label = 'E-mail'

	class Meta:
		model = User
		fields = (
			'first_name',
			'last_name',
			'email',
		)

	def save(self, commit=True):
		user = super(ChangeForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

dtluser/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import RegistrationForm, ChangeForm
from django.contrib.auth.decorators import login_required
from django.conf import settings

@login_required
def profile(request):
	print(settings.MEDIA_ROOT)
	args = {'user': request.user}
	return render(request, 'user/profile.html', args)

def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/user')
	else:
		form = RegistrationForm()

	return render(request, 'user/register.html', {'form': form})

@login_required
def edit(request):
	if request.method == 'POST':
		form = ChangeForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			return redirect('/user')
	else:
		form = ChangeForm(instance=request.user)

	return render(request, 'user/edit.html', {'form': form})

dtluser/templates/user/edit.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} {% trans 'Edit Profile' %} {% endblock %}
{% block content_title %}
<h3 class="d-flex align-items-middle">
	<i class="fas fa-user fa-fw"></i> 
	{% trans 'Edit Profile' %}
</h3> 
<hr/>
{% endblock %}

{% block content %}
<div class="w-50 mx-auto border p-5">
	<form method="post">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<ul>
			{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% for hidden_field in form.hidden_fields %}
		{% if hidden_field.errors %}
		<ul>
			{% for error in hidden_field.errors %}
			<li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{{ hidden_field }}
		{% endfor %}

		{% for field in form %}
		<div class="form-group">
			{{ field.errors }}
			{{ field.label_tag }}
			{{ field }}
		</div>
		{% endfor %}
		
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Salvar" />
			<a href="javascript: history.back();" class="btn btn-danger">Cancelar</a>
		</div>
	</form>
</div>
{% endblock %}

dtluser/templates/user/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} {% trans 'Profile' %} {% endblock %}
{% block content_title %}
<h3 class="d-flex align-items-middle">
	<i class="fas fa-user fa-fw"></i>
	{% trans 'Profile' %}
</h3>
<hr/>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-3 text-center">
		{% if user.profile.picture %}
		<img src="{{ user.profile.picture.url }}" class="img-thumbnail" alt="">
		{% else %}
		<i class="fas fa-user fa-10x m-3 img-thumbnail p-5"></i>
		{% endif %}
		<a href="{% url 'user:edit' %}" class="btn btn-info btn-block">Editar Perfil</a>
	</div>
	<div class="col-md-9 p-3">
		<dl>
			<dt>Nome:</dt>
			<dd>{{ user.first_name }}</dd>
			<dt>Sobrenome:</dt>
			<dd>{{ user.last_name }}</dd>
			<dt>Usuário:</dt>
			<dd>{{ user.username }}</dd>
			<dt>E-mail:</dt>
			<dd>{{ user.email }}</dd>
		</dl>
	</div>
</div>

{% endblock %}

dtluser/templates/user/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} {% trans 'Novo Usuário' %} {% endblock %}
{% block content_title %}
<h3 class="d-flex align-items-middle">
	<i class="fas fa-lock fa-fw"></i> 
	{% trans 'Novo Usuário' %}
</h3> 
<hr/>
{% endblock %}

{% block content %}
<div class="w-50 mx-auto border p-5">
	<form method="post">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<ul>
			{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% for hidden_field in form.hidden_fields %}
		{% if hidden_field.errors %}
		<ul>
			{% for error in hidden_field.errors %}
			<li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{{ hidden_field }}
		{% endfor %}

		<div class="form-group">
			<label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
			<input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.name }}" required="" autocomplete="none" autofocus="" {% if form.first_name.value != None %}value="{{ form.first_name.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.first_name.field.max_length }}"/>
			{{ form.first_name.errors }}
		</div>
		<div class="form-group">
			<label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
			<input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" name="{{ form.last_name.name }}" required="" autocomplete="none" autofocus="" {% if form.last_name.value != None %}value="{{ form.last_name.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.last_name.field.max_length }}"/>
			{{ form.last_name.errors }}
		</div>
		<div class="form-group">
			<label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
			<input type="text" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" required="" autocomplete="none" autofocus="" {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.email.field.max_length }}"/>
			{{ form.email.errors }}
		</div>
		<div class="form-group">
			<label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
			<input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" required="" autocomplete="none" autofocus="" {% if form.username.value != None %}value="{{ form.username.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.username.field.max_length }}"/>
			{{ form.username.errors }}
		</div>
		<div class="form-group">
			<label for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
			<input type="password" class="form-control" id="{{ form.password1.id_for_label }}" name="{{ form.password1.name }}" required="" autocomplete="none" autofocus="" {% if form.password1.value != None %}value="{{ form.password1.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.password1.field.max_length }}"/>
			{{ form.password1.errors }}
		</div>
		<div class="form-group">
			<label for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
			<input type="password" class="form-control" id="{{ form.password2.id_for_label }}" name="{{ form.password2.name }}" required="" autocomplete="none" autofocus="" {% if form.password2.value != None %}value="{{ form.password2.value|stringformat:'s' }}"{% endif %}  maxlength="{{ form.password2.field.max_length }}"/>
			{{ form.password2.errors }}
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Salvar" />
			<a href="javascript: history.back();" class="btn btn-danger">Cancelar</a>
		</div>
	</form>
</div>
{% endblock %}