dartallapy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('dtlauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('dtluser.urls')),
    path('scrapy/', include('dtlscrapy.urls')),
    path('polls/', include('polls.urls')),
    path('customer/', include('dtlcustomer.urls')),
]

dtlcustomer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

dtluser/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
	path('', views.profile , name="profile"),
	path('register/', views.register , name="register"),
	path('edit/', views.edit , name="edit"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from .import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/includes/footer.html
{% block footer %}
    
{% endblock %}

templates/includes/header.html
{% load i18n %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
    <a href="{% url 'home' %}" class="navbar-brand mb-0 h1">Dartalla</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#dtlNavbar" aria-controls="dtlNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="dtlNavbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="{% url 'customer:index' %}" class="nav-link">Clientes</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dtlUserDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user img-thumbnail rounded-circle"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dtlUserDropdown">
                    <a class="dropdown-item" href="{% url 'user:profile' %}">Ver Perfil</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Trocar Senha</a>
                    <hr class="divider"/>
                    <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                </div>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li>
                <a href="{% url 'login' %}" class="btn btn-outline-secondary mr-2">{% trans 'Sign In' %}</a>
            </li>
            <li>
                <a href="{% url 'user:register' %}" class="btn btn-outline-secondary">Registrar</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>
{% endblock %}